- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: demo-rg
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: demo-rg
      name: demo-virtual-network
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: demo-rg
      name: demo-subnet
      address_prefix: "10.0.1.0/24"
      virtual_network: demo-virtual-network
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: demo-rg
      allocation_method: Static
      name: demo-public-ip
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP will be {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows all traffic
    azure_rm_securitygroup:
      resource_group: demo-rg
      name: myNetworkSecurityGroup
      rules:
        - name: AllTraffic
          protocol: Tcp
          destination_port_range: "*"
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: demo-rg
      name: demo-nic
      virtual_network: demo-virtual-network
      subnet: demo-subnet
      public_ip_name: demo-public-ip
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: demo-rg
      name: demo-ansible
      vm_size: Standard_B2s
      admin_username: azureuser
      admin_password: Password1234!
      ssh_password_enabled: true
      network_interfaces: demo-nic
      custom_data: "{{ lookup('file', 'cloud-init.sh') }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '18.04-LTS'
        version: latest