image: maven:3.5.4-jdk-8-alpine
stages:
  - code_analysis
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - .maven
        
before_script:
    - REVISION_STABLE=${CI_COMMIT_TAG}
    - REVISION_UNSTABLE=${CI_COMMIT_REF_SLUG}+sha.${CI_COMMIT_SHA:0:8}
    - export MAVEN_USER_HOME=`pwd`/.maven

sonarqube:issues:
  stage: code_analysis
  script:
    - mvn --batch-mode verify sonar:sonar -DskipTests=true -Drevision=$REVISION_UNSTABLE -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.failure_notification_mode=exit-code
  only:
    - master
sonarqube:publish:
  stage: code_analysis
  script:
    - mvn --batch-mode verify sonar:sonar -Drevision=$REVISION_STABLE -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.failure_notification_mode=exit-code 
    
  only:
    - /^\d+\.\d+\.\d+-rc\.[0-9]+$/
    - /^\d+\.\d+\.\d+$/ 


build:stable:
  stage: build
  artifacts:
    expire_in: 10 mins
  only:
    - /^\d+\.\d+\.\d+-rc\.[0-9]+$/
    - /^\d+\.\d+\.\d+$/
  script:
    - mvn install -B -DskipTests=true -Dmaven.javadoc.skip=true -Drevision=$REVISION_STABLE
