- name: Capture image Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Generalize VM using version >= 2.8
      azure_rm_virtualmachine:
        resource_group: demo-rg
        name: demo-ansible
        generalized: yes

    - name: Create an image from a virtual machine
      azure_rm_image:
        resource_group: demo-rg
        name: imagen-ansible-demo
        source: demo-ansible